// const data = [
//     {
//         id: 'abcd12345',
//         provider_id: 'PRAM_1234',
//         status_id: 1,
//         status: 'Approved',
//         provider: 'Pramerica',
//         partner: 'BHIMA',
//         product: 'Credit Life Insurance',
//         createdDateTime: '2024-06-01T10:15:00',
//         reason: null,
//     },
//     {
//         id: 'efgh56789',
//         provider_id: 'NIVA_5678',
//         status_id: 2,
//         status: 'Waiting for admin approval',
//         provider: 'Niva Bupa',
//         partner: 'Finhaat',
//         product: 'Hospicash',
//         createdDateTime: '2024-06-02T12:30:00',
//         reason: null,
//     },
//     {
//         id: 'ijkl101112',
//         provider_id: 'PRAM_1234',
//         status_id: 3,
//         status: 'On Hold',
//         provider: 'Pramerica',
//         partner: 'BHIMA',
//         product: 'Hospicash',
//         createdDateTime: '2024-06-03T09:45:00',
//         reason: null,
//     },
//     {
//         id: 'mnop131415',
//         provider_id: 'NIVA_5678',
//         status_id: 4,
//         status: 'Rejected',
//         provider: 'Niva Bupa',
//         partner: 'Finhaat',
//         product: 'Credit Life Insurance',
//         createdDateTime: '2024-06-04T14:20:00',
//         reason: 'Allocated to wrong Officer',
//     },
//     {
//         id: 'qrst161718',
//         provider_id: 'PRAM_1234',
//         status_id: 1,
//         status: 'Approved',
//         provider: 'Pramerica',
//         partner: 'BHIMA',
//         product: 'Credit Life Insurance',
//         createdDateTime: '2024-06-05T16:00:00',
//         reason: null,
//     },
//     {
//         id: 'uvwx192021',
//         provider_id: 'NIVA_5678',
//         status_id: 2,
//         status: 'Waiting for admin approval',
//         provider: 'Niva Bupa',
//         partner: 'Finhaat',
//         product: 'Hospicash',
//         createdDateTime: '2024-06-06T11:35:00',
//         reason: null,
//     },
//     {
//         id: 'yzab222324',
//         provider_id: 'PRAM_1234',
//         status_id: 3,
//         status: 'On Hold',
//         provider: 'Pramerica',
//         partner: 'BHIMA',
//         product: 'Hospicash',
//         createdDateTime: '2024-06-07T13:50:00',
//         reason: null,
//     },
//     {
//         id: 'cdef252627',
//         provider_id: 'NIVA_5678',
//         status_id: 4,
//         status: 'Rejected',
//         provider: 'Niva Bupa',
//         partner: 'Finhaat',
//         product: 'Credit Life Insurance',
//         createdDateTime: '2024-06-08T15:25:00',
//         reason: 'Bank Photo not clear',
//     },
//     {
//         id: 'ghij282930',
//         provider_id: 'PRAM_1234',
//         status_id: 1,
//         status: 'Approved',
//         provider: 'Pramerica',
//         partner: 'BHIMA',
//         product: 'Credit Life Insurance',
//         createdDateTime: '2024-06-09T08:10:00',
//         reason: null,
//     },
//     {
//         id: 'klmn313233',
//         provider_id: 'NIVA_5678',
//         status_id: 2,
//         status: 'Waiting for admin approval',
//         provider: 'Niva Bupa',
//         partner: 'Finhaat',
//         product: 'Hospicash',
//         createdDateTime: '2024-06-10T10:40:00',
//         reason: null,
//     },
// ];

// export default data;

const data = [
    {
        id: "prd-3a8fbecc-8a59-482c-96d4-406f0679c9b6",
        providerId: "prv-1a70dfd6-6464-4c32-9f52-ee413ebf37aa",
        provider: "Pramerica",
        partner: "Finhaat",
        name: "Hospicash",
        masterPolicyNumber: "MPN123456",
        minEntryAge: 18,
        maxEntryAge: 65,
        maturityAge: 75,
        policyTenure: 20,
        consentType: "Digital",
        insuranceType: "Single",
        paymentMode: "Cash",
        createdAt: "2024-07-01T04:49:05.421Z",
        updatedAt: "2024-07-01T04:49:05.423Z",
        status: "Approved",
        reason: null,
    },
    {
        id: "prd-dce05a9a-4b7a-40eb-b915-951bd457b5ad",
        providerId: "prv-1a70dfd6-6464-4c32-9f52-ee413ebf37aa",
        provider: "Pramerica",
        partner: "Finhaat",
        name: "Hospicash",
        masterPolicyNumber: "MPN123456",
        minEntryAge: 18,
        maxEntryAge: 65,
        maturityAge: 75,
        policyTenure: 20,
        consentType: "Digital",
        insuranceType: "Single",
        paymentMode: "Cash",
        createdAt: "2024-06-27T17:33:01.813Z",
        updatedAt: "2024-06-27T17:33:01.813Z",
        status: "Rejected",
        reason: "Wrong Officer Allocation",
    },
    {
        id: "prd-49979e07-f1cc-43ee-90ed-af53bfdfd8b6",
        providerId: "prv-1a70dfd6-6464-4c32-9f52-ee413ebf37aa",
        provider: "Pramerica",
        partner: "Finhaat",
        name: "Hospicash",
        masterPolicyNumber: "MPN123456",
        minEntryAge: 18,
        maxEntryAge: 65,
        maturityAge: 75,
        policyTenure: 20,
        consentType: "Digital",
        insuranceType: "Single",
        paymentMode: "Cash",
        createdAt: "2024-06-27T17:32:01.922Z",
        updatedAt: "2024-06-27T17:32:01.922Z",
        status: "Waiting for Admin Approval",
        reason: null,
    },
];

export default data;
